variables:
  IMAGE_NAME: registry.hetzijnet.nl/samsim/matchboxd
  TAG: latest
  DOCKER_HOST: tcp://docker:2375 # Use the Docker-in-Docker daemon
  DOCKER_TLS_CERTDIR: "" # Disable TLS for simplicity

build-and-push:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  script:
    - echo "Building Docker image..."
    - docker build -t "$IMAGE_NAME:$TAG" .
    - echo "Logging in to the container registry..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - echo "Pushing Docker image..."
    - docker push "$IMAGE_NAME:$TAG"
  only:
    - main # Run this job only on the main branch
