services:
  api:
    build: ./api/.
    container_name: matchboxd_api
    # for development purposes
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./api/.:/app
    ports:
      - "8080:8080"
    network_mode: host
  api_db:
    image: postgres
    container_name: matchboxd_db
    environment:
      - POSTGRES_DB=matchboxd_db
      - POSTGRES_USER=matchboxd_db
      - POSTGRES_PASSWORD=123_123
    ports:
      - "5432:5432"
    network_mode: host
  frontend:
    build: ./frontend/.
    ports:
      - "5371:80"

  lb_list:
        image: screeny05/letterboxd-list-radarr:latest
        ports:
            - 5000:5000
        environment:
            - REDIS_URL=redis://Lb_list_redis:6379
        depends_on:
            - Lb_list_redis
  Lb_list_redis:
        image: redis:6.0

networks:
  backend:
    name: backend
    driver: bridge
