services:
  matchboxd:
    build: .
    container_name: matchboxd
    user: ${PUID}:${PGID}
    environment:
      #- RUN_ONCE=true
      - TZ=${TZ}
      - CRON_SCHEDULE=0 8,20 * * *
      - TMDB_API=${TMDB_API}
      - LB_LIST=${LB_LIST}
      - LOCATIONS=${LOCATIONS}
      - GH_TOKEN=${GH_TOKEN} #optional github token for scrapedriver
    volumes:
      - ./web/:/usr/src/app/web
      - ./database:/usr/src/app/database