services:
  matchboxd_api:
    build: ./api/.
    container_name: matchboxd_api
    # for development purposes
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    environment:
      - TZ=${TZ}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - COUNTRY=${COUNTRY}
      - CITY=${CITY}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - CONFIG_PATH=/usr/src/app/api/config.toml
    volumes:
      - ./api/.:/app
      - ./config.toml:/usr/src/app/api/config.toml
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend
    depends_on:
      - matchboxd_db
  matchboxd_db:
    image: postgres
    container_name: matchboxd_db
    environment:
      - TZ=${TZ}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - matchboxd_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
  matchboxd_web:
    container_name: matchboxd_web
    build: ./frontend/.
    environment:
      - TZ=${TZ}
    ports:
      - "5371:80"
    networks:
      - frontend

  lb_list:
    container_name: lb_list
    image: screeny05/letterboxd-list-radarr:latest
    ports:
      - 5000:5000
    environment:
      - TZ=${TZ}
      - REDIS_URL=redis://Lb_list_redis:6379
      - LOG_LEVEL=debug
    depends_on:
      - Lb_list_redis
  Lb_list_redis:
    container_name: lb_list_redis
    image: redis:6.0
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - TZ=${TZ}
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

networks:
  backend:
    name: backend
  frontend:
    name: frontend

volumes:
  matchboxd_db:
    name: matchboxd_db
