services:
  api:
    build: ./api/.
    container_name: cv_lb_api
    # for development purposes
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./api/.:/app
    ports:
      - "8080:8080"
    networks:
      - backend
  api_db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB="cv_lb_db"
      - POSTGRES_USER="cv_lb"
      - POSTGRES_PASSWORD="123_123"
    ports:
      - "5432:5432"
    networks:
      - backend
  frontend:
    build: ./frontend/.
    ports:
      - "5371:80"

networks:
  backend:
    name: backend
    driver: bridge
