export const apiData = {
    "path": "kromsam/watchlist",
    "city": null,
    "films_with_showings": [
        {
            "cities": [
                {
                    "id": 3,
                    "city_slug": "amsterdam",
                    "city_name": "Amsterdam",
                    "country": "nl",
                    "timestamp": "2023-12-17T00:24:41.709148"
                }
            ],
            "showings": [
                {
                    "id": 952,
                    "cv_showing_id": "dfb9cbb1-242a-4b6b-bc71-69dfdbe06017",
                    "start_date": "2023-12-21T18:00:00",
                    "end_date": "2023-12-21T19:40:00",
                    "location_name": "Melkweg",
                    "location_city": "Amsterdam",
                    "ticket_url": null,
                    "information_url": "http://www.melkweg.nl/film",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 4
                },
                {
                    "id": 953,
                    "cv_showing_id": "f637ec14-ab4f-4be8-b84d-42f5835c5696",
                    "start_date": "2023-12-22T18:00:00",
                    "end_date": "2023-12-22T19:40:00",
                    "location_name": "Melkweg",
                    "location_city": "Amsterdam",
                    "ticket_url": null,
                    "information_url": "http://www.melkweg.nl/film",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 4
                },
                {
                    "id": 954,
                    "cv_showing_id": "23e67f96-605e-4270-8a8f-c7033d786c84",
                    "start_date": "2023-12-23T18:00:00",
                    "end_date": "2023-12-23T19:40:00",
                    "location_name": "Melkweg",
                    "location_city": "Amsterdam",
                    "ticket_url": null,
                    "information_url": "http://www.melkweg.nl/film",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 4
                },
                {
                    "id": 1085,
                    "cv_showing_id": "0dfe1728-1037-499a-805c-f2b2cb7cfcc5",
                    "start_date": "2023-12-23T18:30:00",
                    "end_date": "2023-12-23T20:10:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/943407?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 4
                },
                {
                    "id": 1650,
                    "cv_showing_id": "32131521-8f06-4c18-85ac-ed4d03501f8e",
                    "start_date": "2024-01-20T20:30:00",
                    "end_date": "2024-01-20T22:10:00",
                    "location_name": "Eye",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://kaarten.eyefilm.nl/eye/nl/flow_configs/webshop/steps/order/show/946578?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.eyefilm.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 4
                },
                {
                    "id": 1834,
                    "cv_showing_id": "1b1b2b10-5b60-45bb-a095-0b238d0ef3ae",
                    "start_date": "2023-12-24T20:15:00",
                    "end_date": "2023-12-24T21:55:00",
                    "location_name": "Filmhallen",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://www.filmhallen.nl/tickets/105186?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.filmhallen.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 4
                }
            ],
            "id": 4,
            "tmdb_id": 24128,
            "cv_film_id": "0f9b9494-d777-4588-b2ae-19d32a680415",
            "title": "Stop Making Sense",
            "slug": "stop-making-sense",
            "screening_state": null,
            "oneliner": "Het veertigjarige verjaardagsfeestje van hét filmoptreden van Talking Heads.\n\n",
            "img_url": null,
            "imdb_id": "tt0088178",
            "release_year": "1984",
            "clean_title": "/film/stop-making-sense/",
            "adult": false
        },
        {
            "cities": [
                {
                    "id": 3,
                    "city_slug": "amsterdam",
                    "city_name": "Amsterdam",
                    "country": "nl",
                    "timestamp": "2023-12-17T00:24:41.709148"
                }
            ],
            "showings": [
                {
                    "id": 968,
                    "cv_showing_id": "70ae832d-06b5-41fc-bb9a-f47221a6bd4a",
                    "start_date": "2023-12-28T19:00:00",
                    "end_date": "2023-12-28T21:50:00",
                    "location_name": "De Omval Diemen",
                    "location_city": "Amsterdam",
                    "ticket_url": null,
                    "information_url": "http://www.theaterdeomval.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 969,
                    "cv_showing_id": "17118902-bad5-4e8a-877d-17e744df9c24",
                    "start_date": "2024-01-09T19:00:00",
                    "end_date": "2024-01-09T21:50:00",
                    "location_name": "De Omval Diemen",
                    "location_city": "Amsterdam",
                    "ticket_url": null,
                    "information_url": "http://www.theaterdeomval.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1015,
                    "cv_showing_id": "f95596b4-c0e6-49d5-9e7e-7e2cb40918c3",
                    "start_date": "2023-12-17T20:05:00",
                    "end_date": "2023-12-17T22:55:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/940699?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1016,
                    "cv_showing_id": "57c466d6-bc4e-4115-844e-aa15033da1bd",
                    "start_date": "2023-12-18T20:05:00",
                    "end_date": "2023-12-18T22:55:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/940700?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1017,
                    "cv_showing_id": "b2a1f1ce-ac0b-4113-a506-c6992ad89d3b",
                    "start_date": "2023-12-19T20:05:00",
                    "end_date": "2023-12-19T22:55:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/940701?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1018,
                    "cv_showing_id": "de589ef2-33fa-443f-88ed-d363260fabd2",
                    "start_date": "2023-12-20T20:15:00",
                    "end_date": "2023-12-20T23:05:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/940702?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1032,
                    "cv_showing_id": "270a840c-7c0a-4dd0-8595-f84ee2cfa52a",
                    "start_date": "2023-12-18T11:40:00",
                    "end_date": "2023-12-18T14:30:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/940803?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1033,
                    "cv_showing_id": "09b51f36-f5cc-461e-90f7-3de3c3791925",
                    "start_date": "2023-12-19T12:15:00",
                    "end_date": "2023-12-19T15:05:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/940804?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1034,
                    "cv_showing_id": "8c3c7518-60c8-49b0-9806-66c4793b85c4",
                    "start_date": "2023-12-20T12:10:00",
                    "end_date": "2023-12-20T15:00:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/940805?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1094,
                    "cv_showing_id": "3371edcb-a41a-4c5c-b234-8ce6ffc5a53e",
                    "start_date": "2023-12-17T15:40:00",
                    "end_date": "2023-12-17T18:30:00",
                    "location_name": "FC Hyena",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.fchyena.nl/fchyena/nl/flow_configs/fchy_1s/steps/start/show/945508?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "https://fchyena.nl/",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1098,
                    "cv_showing_id": "fe14bc1d-155a-4b85-b203-517c6bcefd3a",
                    "start_date": "2023-12-17T18:45:00",
                    "end_date": "2023-12-17T21:35:00",
                    "location_name": "FC Hyena",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.fchyena.nl/fchyena/nl/flow_configs/fchy_1s/steps/start/show/945512?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "https://fchyena.nl/",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1102,
                    "cv_showing_id": "636b200a-9b07-4b7f-8db7-ea15716b8abe",
                    "start_date": "2023-12-18T14:40:00",
                    "end_date": "2023-12-18T17:30:00",
                    "location_name": "FC Hyena",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.fchyena.nl/fchyena/nl/flow_configs/fchy_1s/steps/start/show/945517?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "https://fchyena.nl/",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1106,
                    "cv_showing_id": "498b4d95-db1f-4117-8075-0e3cec39a011",
                    "start_date": "2023-12-18T19:30:00",
                    "end_date": "2023-12-18T22:20:00",
                    "location_name": "FC Hyena",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.fchyena.nl/fchyena/nl/flow_configs/fchy_1s/steps/start/show/945521?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "https://fchyena.nl/",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1110,
                    "cv_showing_id": "f3f43ee5-883b-4931-93ac-1bc28d0c17e3",
                    "start_date": "2023-12-19T12:10:00",
                    "end_date": "2023-12-19T15:00:00",
                    "location_name": "FC Hyena",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.fchyena.nl/fchyena/nl/flow_configs/fchy_1s/steps/start/show/945526?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "https://fchyena.nl/",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1111,
                    "cv_showing_id": "2a2e693b-1572-41c5-859f-b6a651ef3e2f",
                    "start_date": "2023-12-19T20:10:00",
                    "end_date": "2023-12-19T23:00:00",
                    "location_name": "FC Hyena",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.fchyena.nl/fchyena/nl/flow_configs/fchy_1s/steps/start/show/945530?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "https://fchyena.nl/",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1115,
                    "cv_showing_id": "36ddb82c-f429-44e0-92ba-846e1b3eaeb2",
                    "start_date": "2023-12-20T14:40:00",
                    "end_date": "2023-12-20T17:30:00",
                    "location_name": "FC Hyena",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.fchyena.nl/fchyena/nl/flow_configs/fchy_1s/steps/start/show/945535?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "https://fchyena.nl/",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1119,
                    "cv_showing_id": "cfad58a3-ec51-42d2-bd97-c53a138ed66f",
                    "start_date": "2023-12-20T19:30:00",
                    "end_date": "2023-12-20T22:20:00",
                    "location_name": "FC Hyena",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.fchyena.nl/fchyena/nl/flow_configs/fchy_1s/steps/start/show/945539?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "https://fchyena.nl/",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1134,
                    "cv_showing_id": "28aae199-9ac8-4d8e-8b51-58441ed1e97e",
                    "start_date": "2023-12-17T14:30:00",
                    "end_date": "2023-12-17T17:20:00",
                    "location_name": "The Movies",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://themovies.nl/tickets/104609?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.themovies.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1141,
                    "cv_showing_id": "2d9bf093-5645-488a-86f6-d56041af5084",
                    "start_date": "2023-12-17T19:45:00",
                    "end_date": "2023-12-17T22:35:00",
                    "location_name": "The Movies",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://themovies.nl/tickets/104614?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.themovies.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1152,
                    "cv_showing_id": "a7cb5204-c026-40f0-b12f-37a7afbb80d9",
                    "start_date": "2023-12-18T14:30:00",
                    "end_date": "2023-12-18T17:20:00",
                    "location_name": "The Movies",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://themovies.nl/tickets/104610?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.themovies.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1159,
                    "cv_showing_id": "668481fd-1e76-41b8-8a67-44d9015986dd",
                    "start_date": "2023-12-18T19:45:00",
                    "end_date": "2023-12-18T22:35:00",
                    "location_name": "The Movies",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://themovies.nl/tickets/104615?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.themovies.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1170,
                    "cv_showing_id": "92a5a5a2-2c99-4f99-959b-2136e63abc6b",
                    "start_date": "2023-12-19T14:30:00",
                    "end_date": "2023-12-19T17:20:00",
                    "location_name": "The Movies",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://themovies.nl/tickets/104611?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.themovies.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1177,
                    "cv_showing_id": "61e9c770-8cc1-4fd6-95ab-bd7834d750b3",
                    "start_date": "2023-12-19T19:45:00",
                    "end_date": "2023-12-19T22:35:00",
                    "location_name": "The Movies",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://themovies.nl/tickets/104616?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.themovies.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1188,
                    "cv_showing_id": "d68b1eeb-e91b-4381-9a4a-d5347eae77e2",
                    "start_date": "2023-12-20T14:30:00",
                    "end_date": "2023-12-20T17:20:00",
                    "location_name": "The Movies",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://themovies.nl/tickets/104612?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.themovies.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1196,
                    "cv_showing_id": "5466d513-581e-4c19-b69b-55b4025ebc63",
                    "start_date": "2023-12-20T19:45:00",
                    "end_date": "2023-12-20T22:35:00",
                    "location_name": "The Movies",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://themovies.nl/tickets/104617?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.themovies.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1217,
                    "cv_showing_id": "48db7051-2e6e-414b-8781-8de6f5758987",
                    "start_date": "2023-12-20T11:00:00",
                    "end_date": "2023-12-20T13:50:00",
                    "location_name": "Eye",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://kaarten.eyefilm.nl/eye/nl/flow_configs/webshop/steps/order/show/945926?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.eyefilm.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1241,
                    "cv_showing_id": "0e27bfe6-4c08-456e-9200-d73c63df804b",
                    "start_date": "2023-12-17T19:45:00",
                    "end_date": "2023-12-17T22:35:00",
                    "location_name": "Eye",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://kaarten.eyefilm.nl/eye/nl/flow_configs/webshop/steps/order/show/945983?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.eyefilm.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1341,
                    "cv_showing_id": "4de9ff86-8333-43a1-b037-3c63bd3d7300",
                    "start_date": "2023-12-17T12:30:00",
                    "end_date": "2023-12-17T15:20:00",
                    "location_name": "Filmhallen",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://www.filmhallen.nl/tickets/105037?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.filmhallen.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1361,
                    "cv_showing_id": "2c610168-d5e9-465f-8ca7-f6824682695a",
                    "start_date": "2023-12-17T19:45:00",
                    "end_date": "2023-12-17T22:35:00",
                    "location_name": "Filmhallen",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://www.filmhallen.nl/tickets/105057?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.filmhallen.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1379,
                    "cv_showing_id": "07c429cc-8dda-4dd0-97f4-9371a824a11b",
                    "start_date": "2023-12-18T12:30:00",
                    "end_date": "2023-12-18T15:20:00",
                    "location_name": "Filmhallen",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://www.filmhallen.nl/tickets/105038?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.filmhallen.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1398,
                    "cv_showing_id": "8c16c7b4-3e80-4976-8c2a-e335783ee533",
                    "start_date": "2023-12-18T19:45:00",
                    "end_date": "2023-12-18T22:35:00",
                    "location_name": "Filmhallen",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://www.filmhallen.nl/tickets/105058?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.filmhallen.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1418,
                    "cv_showing_id": "40bae99c-b1c2-4112-8687-c2ea3fe4bff5",
                    "start_date": "2023-12-19T12:30:00",
                    "end_date": "2023-12-19T15:20:00",
                    "location_name": "Filmhallen",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://www.filmhallen.nl/tickets/105039?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.filmhallen.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1436,
                    "cv_showing_id": "1f987ae9-78b0-43fd-894a-ddaad449f43c",
                    "start_date": "2023-12-19T19:45:00",
                    "end_date": "2023-12-19T22:35:00",
                    "location_name": "Filmhallen",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://www.filmhallen.nl/tickets/105059?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.filmhallen.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1456,
                    "cv_showing_id": "1aeb3457-95ff-41e5-a221-1d5542351201",
                    "start_date": "2023-12-20T12:30:00",
                    "end_date": "2023-12-20T15:20:00",
                    "location_name": "Filmhallen",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://www.filmhallen.nl/tickets/105040?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.filmhallen.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1474,
                    "cv_showing_id": "b6bcf5a4-d7e8-4923-8e8c-c9ffc0f2f9bf",
                    "start_date": "2023-12-20T19:45:00",
                    "end_date": "2023-12-20T22:35:00",
                    "location_name": "Filmhallen",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://www.filmhallen.nl/tickets/105060?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.filmhallen.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1484,
                    "cv_showing_id": "9e3269ff-8e0e-4ca9-abd5-750213827a9a",
                    "start_date": "2023-12-17T15:00:00",
                    "end_date": "2023-12-17T17:50:00",
                    "location_name": "Rialto VU",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://rialtofilm.nl/nl/shop/nl-NL%2FAccount%2FLogin%3FReturnUrl%3D%2Fnl-NL%2FShow%2FDetails%2F11892604&utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "https://rialtofilm.nl/rialto-vu",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1485,
                    "cv_showing_id": "2f39a979-9d92-43a4-8f8a-17155551106c",
                    "start_date": "2023-12-17T18:15:00",
                    "end_date": "2023-12-17T21:05:00",
                    "location_name": "Rialto VU",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://rialtofilm.nl/nl/shop/nl-NL%2FAccount%2FLogin%3FReturnUrl%3D%2Fnl-NL%2FShow%2FDetails%2F11892610&utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "https://rialtofilm.nl/rialto-vu",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1490,
                    "cv_showing_id": "024de8af-6489-499f-8749-590ea1114deb",
                    "start_date": "2023-12-18T19:15:00",
                    "end_date": "2023-12-18T22:05:00",
                    "location_name": "Rialto VU",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://rialtofilm.nl/nl/shop/nl-NL%2FAccount%2FLogin%3FReturnUrl%3D%2Fnl-NL%2FShow%2FDetails%2F11892615&utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "https://rialtofilm.nl/rialto-vu",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1494,
                    "cv_showing_id": "67950bb5-2d36-4116-a36b-3e3caf593e0c",
                    "start_date": "2023-12-19T19:15:00",
                    "end_date": "2023-12-19T22:05:00",
                    "location_name": "Rialto VU",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://rialtofilm.nl/nl/shop/nl-NL%2FAccount%2FLogin%3FReturnUrl%3D%2Fnl-NL%2FShow%2FDetails%2F11892600&utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "https://rialtofilm.nl/rialto-vu",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1496,
                    "cv_showing_id": "60bc3d01-587f-436d-b06b-ffae1451e4bc",
                    "start_date": "2023-12-20T19:15:00",
                    "end_date": "2023-12-20T22:05:00",
                    "location_name": "Rialto VU",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://rialtofilm.nl/nl/shop/nl-NL%2FAccount%2FLogin%3FReturnUrl%3D%2Fnl-NL%2FShow%2FDetails%2F11892617&utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "https://rialtofilm.nl/rialto-vu",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1518,
                    "cv_showing_id": "0a17d655-9dad-4a2b-8818-b94e86633dff",
                    "start_date": "2023-12-17T11:25:00",
                    "end_date": "2023-12-17T14:15:00",
                    "location_name": "Studio/K",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.studio-k.nu/studiok/nl/flow_configs/webshop/steps/start/show/944907?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.studio-k.nu",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1525,
                    "cv_showing_id": "6e03fdd3-8b09-43b5-a969-53df10851f2f",
                    "start_date": "2023-12-18T14:20:00",
                    "end_date": "2023-12-18T17:10:00",
                    "location_name": "Studio/K",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.studio-k.nu/studiok/nl/flow_configs/webshop/steps/start/show/944923?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.studio-k.nu",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1552,
                    "cv_showing_id": "0f9d675c-9651-42e5-a781-31642140c3c0",
                    "start_date": "2023-12-17T19:30:00",
                    "end_date": "2023-12-17T22:20:00",
                    "location_name": "Studio/K",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.studio-k.nu/studiok/nl/flow_configs/webshop/steps/start/show/944916?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.studio-k.nu",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1556,
                    "cv_showing_id": "23b55a8b-0407-4059-9630-4503f2c61974",
                    "start_date": "2023-12-19T14:20:00",
                    "end_date": "2023-12-19T17:10:00",
                    "location_name": "Studio/K",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.studio-k.nu/studiok/nl/flow_configs/webshop/steps/start/show/944965?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.studio-k.nu",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1559,
                    "cv_showing_id": "c7000845-30b4-477f-80f2-14df01953ce5",
                    "start_date": "2023-12-19T20:05:00",
                    "end_date": "2023-12-19T22:55:00",
                    "location_name": "Studio/K",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.studio-k.nu/studiok/nl/flow_configs/webshop/steps/start/show/944974?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.studio-k.nu",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1561,
                    "cv_showing_id": "624498f3-050c-4a79-8c1a-c293161c5b0d",
                    "start_date": "2023-12-20T14:20:00",
                    "end_date": "2023-12-20T17:10:00",
                    "location_name": "Studio/K",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.studio-k.nu/studiok/nl/flow_configs/webshop/steps/start/show/944982?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.studio-k.nu",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1566,
                    "cv_showing_id": "4f045b58-c041-4aa4-a440-c65adc738b31",
                    "start_date": "2023-12-20T20:05:00",
                    "end_date": "2023-12-20T22:55:00",
                    "location_name": "Studio/K",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.studio-k.nu/studiok/nl/flow_configs/webshop/steps/start/show/944988?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.studio-k.nu",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1632,
                    "cv_showing_id": "96c5b7a7-4a63-4860-a2c1-51dceeadbc53",
                    "start_date": "2023-12-19T15:10:00",
                    "end_date": "2023-12-19T18:00:00",
                    "location_name": "Cinema De Vlugt",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://zl8.za.jewellabs.net/cinemadevlugt/nl/flow_configs/tickets/steps/start/show/945351?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "https://www.cinemadevlugt.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1690,
                    "cv_showing_id": "fd3e891a-02df-4c92-9caa-8354acb53126",
                    "start_date": "2023-12-21T15:00:00",
                    "end_date": "2023-12-21T17:50:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/945402?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1691,
                    "cv_showing_id": "35122b5d-8b7d-45a3-ac9e-35d3d518a2a8",
                    "start_date": "2023-12-23T14:15:00",
                    "end_date": "2023-12-23T17:05:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/945403?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1692,
                    "cv_showing_id": "db926c9c-5efc-4f44-87f8-759c79004de9",
                    "start_date": "2023-12-24T14:15:00",
                    "end_date": "2023-12-24T17:05:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/945404?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1693,
                    "cv_showing_id": "2235ac00-38db-4a7c-accc-a50f622ff962",
                    "start_date": "2023-12-26T14:25:00",
                    "end_date": "2023-12-26T17:15:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/945405?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1694,
                    "cv_showing_id": "805b876e-9e94-4c89-b1d8-78b37c7e408b",
                    "start_date": "2023-12-27T14:25:00",
                    "end_date": "2023-12-27T17:15:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/945406?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1785,
                    "cv_showing_id": "bf4a824f-2dd1-4b00-bdeb-e8e32799dfca",
                    "start_date": "2023-12-29T12:00:00",
                    "end_date": "2023-12-29T14:50:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/947051?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1786,
                    "cv_showing_id": "7ca9d48a-9086-4d06-a070-989ac06805dd",
                    "start_date": "2023-12-30T12:00:00",
                    "end_date": "2023-12-30T14:50:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/947052?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1787,
                    "cv_showing_id": "6b1cf6de-a01d-416d-9bbe-81fa4002d480",
                    "start_date": "2023-12-28T11:45:00",
                    "end_date": "2023-12-28T14:35:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/947055?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1851,
                    "cv_showing_id": "cb536ab6-0466-4e5d-8a1d-6fef9e4c41f9",
                    "start_date": "2023-12-21T19:45:00",
                    "end_date": "2023-12-21T22:35:00",
                    "location_name": "FC Hyena",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.fchyena.nl/fchyena/nl/flow_configs/fchy_1s/steps/start/show/947238?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "https://fchyena.nl/",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1855,
                    "cv_showing_id": "5686d8b3-214f-495e-8a97-4598e174c758",
                    "start_date": "2023-12-21T14:50:00",
                    "end_date": "2023-12-21T17:40:00",
                    "location_name": "FC Hyena",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.fchyena.nl/fchyena/nl/flow_configs/fchy_1s/steps/start/show/947242?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "https://fchyena.nl/",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                },
                {
                    "id": 1857,
                    "cv_showing_id": "4d09e9ae-1569-4f03-a70a-4982b6e765e4",
                    "start_date": "2023-12-21T11:50:00",
                    "end_date": "2023-12-21T14:40:00",
                    "location_name": "FC Hyena",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.fchyena.nl/fchyena/nl/flow_configs/fchy_1s/steps/start/show/947244?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "https://fchyena.nl/",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 12
                }
            ],
            "id": 12,
            "tmdb_id": 753342,
            "cv_film_id": "f7863a2d-05f2-49ef-8d5f-f6879286e4e6",
            "title": "Napoleon",
            "slug": "napoleon",
            "screening_state": null,
            "oneliner": "Een nieuw filmepos over de Franse generaal en keizer, met Joaquin Phoenix in de hoofdrol. \n\n",
            "img_url": null,
            "imdb_id": "tt13287846",
            "release_year": "2023",
            "clean_title": "/film/napoleon-2023/",
            "adult": false
        },
        {
            "cities": [
                {
                    "id": 3,
                    "city_slug": "amsterdam",
                    "city_name": "Amsterdam",
                    "country": "nl",
                    "timestamp": "2023-12-17T00:24:41.709148"
                }
            ],
            "showings": [
                {
                    "id": 996,
                    "cv_showing_id": "e5c05738-af04-4250-a7da-900ea5007f8e",
                    "start_date": "2023-12-30T13:30:00",
                    "end_date": "2023-12-30T15:35:00",
                    "location_name": "De Uitkijk",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.uitkijk.nl/uitkijk/nl/flow_configs/webshop/steps/start/show/939732?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.uitkijk.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 22
                }
            ],
            "id": 22,
            "tmdb_id": 13384,
            "cv_film_id": "9e948112-9833-4d20-a4af-ed841a80647d",
            "title": "Kes",
            "slug": "kes",
            "screening_state": null,
            "oneliner": "De tweede film van Ken Loach, gemaakt in een natuurlijke, sociaal-realistische stijl.",
            "img_url": null,
            "imdb_id": "tt0064541",
            "release_year": "1969",
            "clean_title": "/film/kes/",
            "adult": false
        },
        {
            "cities": [
                {
                    "id": 3,
                    "city_slug": "amsterdam",
                    "city_name": "Amsterdam",
                    "country": "nl",
                    "timestamp": "2023-12-17T00:24:41.709148"
                }
            ],
            "showings": [
                {
                    "id": 1003,
                    "cv_showing_id": "8ebf3f7e-bd3d-4e8a-9f4f-fc6e7228342b",
                    "start_date": "2023-12-17T15:20:00",
                    "end_date": "2023-12-17T17:45:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/940691?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 27
                },
                {
                    "id": 1080,
                    "cv_showing_id": "b95260c3-d06a-4fbc-8635-4edd02b499ba",
                    "start_date": "2023-12-27T15:15:00",
                    "end_date": "2023-12-27T17:40:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/943386?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 27
                },
                {
                    "id": 1729,
                    "cv_showing_id": "8c94188c-ce20-4aef-8023-696c93478e06",
                    "start_date": "2023-12-26T20:30:00",
                    "end_date": "2023-12-26T22:55:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/945415?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 27
                },
                {
                    "id": 1776,
                    "cv_showing_id": "52607cf5-e549-479a-b64d-013a1c3f7b2e",
                    "start_date": "2023-12-29T20:15:00",
                    "end_date": "2023-12-29T22:40:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/947034?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 27
                },
                {
                    "id": 1821,
                    "cv_showing_id": "256d0700-361a-417b-974b-0cdfa78fa54b",
                    "start_date": "2023-12-31T10:00:00",
                    "end_date": "2023-12-31T12:25:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/947117?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 27
                }
            ],
            "id": 27,
            "tmdb_id": 128,
            "cv_film_id": "f95c3725-fbec-4d45-9d93-47376ad43ff5",
            "title": "Princess Mononoke",
            "slug": "princess-mononoke",
            "screening_state": null,
            "oneliner": "Mythische bosgoden vechten het uit met de geïndustrialiseerde mens in dit magnum opus van animatiemeester Miyazaki.",
            "img_url": "https://culturekit-assets.imgix.net/1/assets/c86726c4-9454-41e4-9d6a-c72959758cae.jpg",
            "imdb_id": "tt0119698",
            "release_year": "1997",
            "clean_title": "/film/princess-mononoke/",
            "adult": false
        },
        {
            "cities": [
                {
                    "id": 3,
                    "city_slug": "amsterdam",
                    "city_name": "Amsterdam",
                    "country": "nl",
                    "timestamp": "2023-12-17T00:24:41.709148"
                }
            ],
            "showings": [
                {
                    "id": 1040,
                    "cv_showing_id": "73ae1d41-3f5a-48e9-9b13-d13bb7c6dfe8",
                    "start_date": "2023-12-19T20:30:00",
                    "end_date": "2023-12-19T23:05:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/940818?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 39
                },
                {
                    "id": 1704,
                    "cv_showing_id": "1c17b611-041d-493a-8c7a-b147ea3363bb",
                    "start_date": "2023-12-26T20:00:00",
                    "end_date": "2023-12-26T22:35:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/946482?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 39
                },
                {
                    "id": 1808,
                    "cv_showing_id": "d50bb276-ba20-4160-ad58-bf916781732a",
                    "start_date": "2023-12-30T12:15:00",
                    "end_date": "2023-12-30T14:50:00",
                    "location_name": "LAB111",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.lab111.nl/labcinema/nl/flow_configs/webshop/steps/start/show/947092?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.lab111.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 39
                }
            ],
            "id": 39,
            "tmdb_id": 1541,
            "cv_film_id": "9e225494-f0a5-4e91-99e6-45ca633f1fd2",
            "title": "Thelma & Louise",
            "slug": "thelma-louise",
            "screening_state": null,
            "oneliner": "Ridley Scotts geslaagde feministische variant op het buddythema, verpakt in een roadmovie.\n\n",
            "img_url": null,
            "imdb_id": "tt0103074",
            "release_year": "1991",
            "clean_title": "/film/thelma-louise/",
            "adult": false
        },
        {
            "cities": [
                {
                    "id": 3,
                    "city_slug": "amsterdam",
                    "city_name": "Amsterdam",
                    "country": "nl",
                    "timestamp": "2023-12-17T00:24:41.709148"
                }
            ],
            "showings": [
                {
                    "id": 1603,
                    "cv_showing_id": "d85a148f-e4d5-4338-be7f-295921078bab",
                    "start_date": "2023-12-18T09:15:00",
                    "end_date": "2023-12-18T11:00:00",
                    "location_name": "De Balie",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.debalie.nl/nl-NL/Show/Details/11830545?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "www.debalie.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 78
                },
                {
                    "id": 1611,
                    "cv_showing_id": "d78dcf11-eb30-49dc-b021-d9db441743a5",
                    "start_date": "2023-12-19T11:15:00",
                    "end_date": "2023-12-19T13:00:00",
                    "location_name": "De Balie",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.debalie.nl/nl-NL/Show/Details/11830554?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "www.debalie.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 78
                },
                {
                    "id": 1618,
                    "cv_showing_id": "5df79c72-1861-4815-8380-be7e90913dcb",
                    "start_date": "2023-12-20T11:15:00",
                    "end_date": "2023-12-20T13:00:00",
                    "location_name": "De Balie",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://tickets.debalie.nl/nl-NL/Show/Details/11830555?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "www.debalie.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 78
                },
                {
                    "id": 1892,
                    "cv_showing_id": "9a7ce481-0c47-4bc4-b3e6-e5e9f88cf95b",
                    "start_date": "2023-12-21T11:45:00",
                    "end_date": "2023-12-21T13:30:00",
                    "location_name": "Eye",
                    "location_city": "Amsterdam",
                    "ticket_url": "https://kaarten.eyefilm.nl/eye/nl/flow_configs/webshop/steps/order/show/947541?utm_source=Cineville&utm_campaign=ticketlink",
                    "information_url": "http://www.eyefilm.nl",
                    "screening_info": null,
                    "additional_info": null,
                    "film_id": 78
                }
            ],
            "id": 78,
            "tmdb_id": 1112547,
            "cv_film_id": "8dfda030-13c4-403f-8398-644cc82b6176",
            "title": "Anselm",
            "slug": "anselm",
            "screening_state": null,
            "oneliner": "Twee jaar uit het leven van kunstenaar Anselm Kiefer, gefilmd door Wim Wenders. \n\n",
            "img_url": "https://culturekit-assets.imgix.net/1/assets/5c6ca171-14d0-4128-bfe9-bcadb7625f30.jpg",
            "imdb_id": "tt27502250",
            "release_year": "2023",
            "clean_title": "/film/anselm/",
            "adult": false
        },
        {
            "cities": [
                {
                    "id": 3,
                    "city_slug": "amsterdam",
                    "city_name": "Amsterdam",
                    "country": "nl",
                    "timestamp": "2023-12-17T00:24:41.709148"
                }
            ],
            "showings": [],
            "id": 105,
            "tmdb_id": 18148,
            "cv_film_id": "4e1f9073-76af-48cf-9862-b8b3a9c85ef1",
            "title": "Tokyo Story",
            "slug": "tokyo-story",
            "screening_state": null,
            "oneliner": "Het diep ontroerende meesterwerk *Tokyo Story* tekent de sociale mores in het naoorlogse Tokio.\n\n",
            "img_url": null,
            "imdb_id": "tt0046438",
            "release_year": "1953",
            "clean_title": "/film/tokyo-story/",
            "adult": false
        },
        {
            "cities": [
                {
                    "id": 3,
                    "city_slug": "amsterdam",
                    "city_name": "Amsterdam",
                    "country": "nl",
                    "timestamp": "2023-12-17T00:24:41.709148"
                }
            ],
            "showings": [],
            "id": 107,
            "tmdb_id": 345,
            "cv_film_id": "972e8420-6a8e-4dc6-a87d-929844b0cfac",
            "title": "Eyes Wide Shut",
            "slug": "eyes-wide-shut",
            "screening_state": null,
            "oneliner": "De laatste film van Stanley Kubrick.\n\n",
            "img_url": "https://culturekit-assets.imgix.net/1/assets/c9b52ad0-a4c3-46a7-851f-c0a43b58e59b.jpg",
            "imdb_id": "tt0120663",
            "release_year": "1999",
            "clean_title": "/film/eyes-wide-shut/",
            "adult": false
        },
        {
            "cities": [
                {
                    "id": 3,
                    "city_slug": "amsterdam",
                    "city_name": "Amsterdam",
                    "country": "nl",
                    "timestamp": "2023-12-17T00:24:41.709148"
                }
            ],
            "showings": [],
            "id": 95,
            "tmdb_id": 872,
            "cv_film_id": "d7c607c2-c496-44cb-a62d-c0a43bb4d19f",
            "title": "Singin' in the Rain",
            "slug": "singin-rain",
            "screening_state": null,
            "oneliner": "Een spetterende klassieker in overdadige Technicolor.\n\n",
            "img_url": null,
            "imdb_id": "tt0045152",
            "release_year": "1952",
            "clean_title": "/film/singin-in-the-rain/",
            "adult": false
        },
        {
            "cities": [
                {
                    "id": 3,
                    "city_slug": "amsterdam",
                    "city_name": "Amsterdam",
                    "country": "nl",
                    "timestamp": "2023-12-17T00:24:41.709148"
                }
            ],
            "showings": [],
            "id": 126,
            "tmdb_id": 49964,
            "cv_film_id": "94070634-1d8b-4642-8211-ba2e054bbff5",
            "title": "Where Is the Friend's House?",
            "slug": "where-is-the-friends-house",
            "screening_state": null,
            "oneliner": "Een ogenschijnlijk simpel verhaal dat in diepere zin gaat over loyaliteit en een gevoel van onderlinge plicht onder het Iraanse volk.\n\n",
            "img_url": null,
            "imdb_id": "tt0093342",
            "release_year": "1987",
            "clean_title": "/film/where-is-the-friends-house/",
            "adult": false
        }
    ]
};